# Generated by Django 3.0.4 on 2020-03-08 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='friendly name of a service')),
                ('is_capability', models.BooleanField(default=False, verbose_name='if true makes the service a capability which is a business deliverable')),
                ('description', models.CharField(max_length=2048, verbose_name='what this service is responsible for')),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed_at', models.DateTimeField(auto_created=True)),
                ('value', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('planned_maintenance', 'Planned Maintenance'), ('unplanned_maintenance', 'Unplanned Maintenance'), ('degraded_warning', 'Degraded - Warning'), ('degraded_critical', 'Degraded - Critical')], default='up', max_length=128)),
                ('forecast_change_date', models.DateTimeField(null=True, verbose_name='Time this state is expected to change')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('depends_on', 'Depends On'), ('dependent', 'Dependent')], default='depends_on', max_length=128)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_service', to='dashboard.Service')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_service', to='dashboard.Service')),
            ],
        ),
    ]
