# Generated by Django 3.0.4 on 2020-03-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='relation_type',
            field=models.CharField(choices=[('depends_on', 'Depends On'), ('dependent', 'dependent')], default='depends_on', max_length=128),
        ),
    ]
