# Generated by Django 3.0.4 on 2020-03-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='public',
            field=models.BooleanField(default=False, verbose_name='if true will allow the service to be viewed if not authenticated'),
        ),
        migrations.AlterField(
            model_name='state',
            name='forecast_change_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time this state is expected to change'),
        ),
    ]
