# Generated by Django 3.0.4 on 2020-03-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_statechange_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='statecomment',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statecomment',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statecomment',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
